"""2023-07-21

Revision ID: 03c1ffef1d5c
Revises: 7d807b9dcc4b
Create Date: 2023-07-21 19:01:54.275606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c1ffef1d5c'
down_revision = '7d807b9dcc4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('counterparties', 'okpo')
    op.drop_column('counterparties', 'kpp')
    op.drop_column('counterparties', 'ogrn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('counterparties', sa.Column('ogrn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('counterparties', sa.Column('kpp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('counterparties', sa.Column('okpo', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
