"""empty message

Revision ID: 20e79a474d9f
Revises: ce396644afc2
Create Date: 2023-07-12 23:56:43.164504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e79a474d9f'
down_revision = 'ce396644afc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
