"""2023-07-23

Revision ID: 330619494019
Revises: 5c1c915d686d
Create Date: 2023-07-23 11:58:43.432510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '330619494019'
down_revision = '5c1c915d686d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('counterparty', sa.String(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'counterparties', ['counterparty'], ['ms_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'counterparty')
    # ### end Alembic commands ###
