"""empty message

Revision ID: 4dffd9ef494a
Revises: 20e79a474d9f
Create Date: 2023-07-13 00:20:17.296506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dffd9ef494a'
down_revision = '20e79a474d9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
