"""2023-07-23

Revision ID: 5c1c915d686d
Revises: 8b6f642aa377
Create Date: 2023-07-23 11:57:26.562688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1c915d686d'
down_revision = '8b6f642aa377'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ms_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ms_id')
    )
    op.create_table('purchase_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_ms_id', sa.String(), nullable=False),
    sa.Column('item_ms_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sum', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_ms_id'], ['items.ms_id'], ),
    sa.ForeignKeyConstraint(['purchase_ms_id'], ['purchases.ms_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_details')
    op.drop_table('purchases')
    # ### end Alembic commands ###
