"""init1

Revision ID: 810f416d83ea
Revises: f8ce667a8586
Create Date: 2023-07-06 15:58:56.960378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810f416d83ea'
down_revision = 'f8ce667a8586'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_registered', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_registered')
    # ### end Alembic commands ###
