"""2023-07-21

Revision ID: 865ccae0ceb7
Revises: 4dffd9ef494a
Create Date: 2023-07-21 13:53:02.440044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865ccae0ceb7'
down_revision = '4dffd9ef494a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
