"""2023-07-21

Revision ID: 8b6f642aa377
Revises: 03c1ffef1d5c
Create Date: 2023-07-21 19:43:37.561078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6f642aa377'
down_revision = '03c1ffef1d5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('counterparty', sa.String(), nullable=False))
    op.create_foreign_key(None, 'orders', 'counterparties', ['counterparty'], ['ms_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'counterparty')
    # ### end Alembic commands ###
