"""2023-07-23

Revision ID: d511373c2587
Revises: 330619494019
Create Date: 2023-07-23 12:18:56.500810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd511373c2587'
down_revision = '330619494019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'name')
    # ### end Alembic commands ###
