"""init

Revision ID: ea929cbc219f
Revises: 125b5266f8a2
Create Date: 2023-07-08 20:03:47.782518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea929cbc219f'
down_revision = '125b5266f8a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_ms_token_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_ms_token_key', 'users', ['ms_token'])
    # ### end Alembic commands ###
